/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CwsButton {
    /**
    * Autofocus state
    */
    'autofocus': boolean;
    /**
    * Disabled state, not applicable if the component receive the `href` prop
    */
    'disabled': boolean;
    /**
    * href to redirect user. It render an anchor tag (`<a></a>`) instead of a button one
    */
    'href'?: string;
    /**
    * Button size
    */
    'size': 'lg' | 'md' | 'sm';
    /**
    * Button type, not applicable if the component receive `href` prop
    */
    'type': 'button' | 'submit' | 'reset';
    /**
    * Button style
    */
    'variant': 'primary' | 'secondary';
  }
  interface CwsFieldText {
    /**
    * Disabled state
    */
    'disabled': boolean;
    /**
    * Label
    */
    'label': string;
    /**
    * Input value
    */
    'value': string;
  }
}

declare global {


  interface HTMLCwsButtonElement extends Components.CwsButton, HTMLStencilElement {}
  var HTMLCwsButtonElement: {
    prototype: HTMLCwsButtonElement;
    new (): HTMLCwsButtonElement;
  };

  interface HTMLCwsFieldTextElement extends Components.CwsFieldText, HTMLStencilElement {}
  var HTMLCwsFieldTextElement: {
    prototype: HTMLCwsFieldTextElement;
    new (): HTMLCwsFieldTextElement;
  };
  interface HTMLElementTagNameMap {
    'cws-button': HTMLCwsButtonElement;
    'cws-field-text': HTMLCwsFieldTextElement;
  }
}

declare namespace LocalJSX {
  interface CwsButton extends JSXBase.HTMLAttributes<HTMLCwsButtonElement> {
    /**
    * Autofocus state
    */
    'autofocus'?: boolean;
    /**
    * Disabled state, not applicable if the component receive the `href` prop
    */
    'disabled'?: boolean;
    /**
    * href to redirect user. It render an anchor tag (`<a></a>`) instead of a button one
    */
    'href'?: string;
    /**
    * Button size
    */
    'size'?: 'lg' | 'md' | 'sm';
    /**
    * Button type, not applicable if the component receive `href` prop
    */
    'type'?: 'button' | 'submit' | 'reset';
    /**
    * Button style
    */
    'variant'?: 'primary' | 'secondary';
  }
  interface CwsFieldText extends JSXBase.HTMLAttributes<HTMLCwsFieldTextElement> {
    /**
    * Disabled state
    */
    'disabled'?: boolean;
    /**
    * Label
    */
    'label'?: string;
    /**
    * Input value
    */
    'value'?: string;
  }

  interface IntrinsicElements {
    'cws-button': CwsButton;
    'cws-field-text': CwsFieldText;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


